# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sebastián Valencia Sierra"
resume_title:                   "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sebasvalencia726@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+57 3172933325"
resume_contact_address:         "79B Street #42 - 262, Apartment 3B, Laure Building, Barranquilla"

resume_header_contact_info:     "79B Street #42 - 262, Apartment 3B, Barranquilla • +57 3172933325 • sebasvalencia726@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p align='justify'>I am a DevOps Engineer with 2 years of experience designing and implementing CI/CD pipelines for a technology migration project from on-premise installations to AWS cloud using Azure DevOps. I have experience in implementing all stages of the DevOps cycle, including code integration, static analysis, dependency checks, compilation, packaging, and artifact repository publication. I have also configured the deployment stages in development, certification, and production environments, implemented acceptance, performance, and end-to-end testing, and managed the rollback stage.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_proeficient_in:  true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sebastiandevops"
  resume_twitter_url:           "http://twitter.com/ajinomano"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sebastianvalenciasierra"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://sebastiandevops.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
